# Cloud Build configuration for deploying to Cloud Run
# 
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml
#
# Prerequisites:
#   - Service account with Cloud Run Admin and Service Account User roles
#   - BigQuery views: v_thread_list, v_monthly_thread_aggregates
#   - Service account attached to Cloud Run with BigQuery permissions

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thread-analytics-api:$SHORT_SHA', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/thread-analytics-api:$SHORT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'thread-analytics-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/thread-analytics-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'cloud-run-frontend-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,BIGQUERY_DATASET_ID=your-dataset,BIGQUERY_THREAD_LIST_VIEW=v_thread_list,BIGQUERY_MONTHLY_AGGREGATES_VIEW=v_monthly_thread_aggregates'
      - '--set-env-vars'
      - 'FRONTEND_URL=https://your-frontend-domain.com'

images:
  - 'gcr.io/$PROJECT_ID/thread-analytics-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

